<a href="https://colab.research.google.com/github/youngbean0519/Self-Project/blob/main/notebooks/04_tfifd_logistic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/youngbean0519/Self-Project.git

Cloning into 'Self-Project'...
remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 58 (delta 15), reused 48 (delta 9), pack-reused 0 (from 0)
Receiving objects: 100% (58/58), 472.47 KiB | 8.91 MiB/s, done.
Resolving deltas: 100% (15/15), done.

In [2]:
%cd Self-Project/
%ls

/content/Self-Project
notebooks/  README.md  requirements.txt  results/  src/  test.py

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import os
import sys

PROJECT_DIR = "/content/Self-Project"
SRC_DIR = os.path.join(PROJECT_DIR, "src")
RESULTS_DIR = os.path.join(PROJECT_DIR, "results")
DATA_DIR = "/content/drive/MyDrive/26_KOTE/data"
ARTIFACT_DIR = "/content/drive/MyDrive/26_KOTE/artifacts/week4_lr"

sys.path.append(PROJECT_DIR)
sys.path.append(SRC_DIR)

print("PROJECT_DIR:", PROJECT_DIR)
print("SRC_DIR:", SRC_DIR)
print("RESULTS_DIR:", RESULTS_DIR)
print("DATA_DIR:", DATA_DIR)
print("ARTIFACT_DIR:", ARTIFACT_DIR)

PROJECT_DIR: /content/Self-Project
SRC_DIR: /content/Self-Project/src
RESULTS_DIR: /content/Self-Project/results
DATA_DIR: /content/drive/MyDrive/26_KOTE/data
ARTIFACT_DIR: /content/drive/MyDrive/26_KOTE/artifacts/week4_lr

In [5]:
import preprocessing.text as text_preprocessing
import preprocessing.labels as preprocessing_labels
import evaluation.metrics as metrics
import utils.labels as utils_labels

In [6]:
import time
import json
import joblib
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier

In [7]:
train_path = os.path.join(DATA_DIR, "train.tsv")
val_path = os.path.join(DATA_DIR, "val.tsv")
test_path = os.path.join(DATA_DIR, "test.tsv")

train_df = pd.read_csv(train_path, sep="\t", header=None, names=["id", "text", "labels"])
val_df = pd.read_csv(val_path, sep="\t", header=None, names=["id", "text", "labels"])
test_df = pd.read_csv(test_path, sep="\t", header=None, names=["id", "text", "labels"])

print("train:", train_df.shape)
print("val:", val_df.shape)
print("test:", test_df.shape)

train: (40000, 3)
val: (5000, 3)
test: (5000, 3)

In [8]:
NUM_LABELS = 44

train_label_lists = train_df["labels"].apply(preprocessing_labels.parse_label_ids).tolist()
val_label_lists = val_df["labels"].apply(preprocessing_labels.parse_label_ids).tolist()
test_label_lists = test_df["labels"].apply(preprocessing_labels.parse_label_ids).tolist()

y_train, mlb = preprocessing_labels.encode_multilabels(train_label_lists, NUM_LABELS)
y_val = mlb.transform(val_label_lists)
y_test = mlb.transform(test_label_lists)

print("y_train:", y_train.shape)
print("y_val:", y_val.shape)
print("y_test:", y_test.shape)

y_train: (40000, 44)
y_val: (5000, 44)
y_test: (5000, 44)

In [9]:
def make_preprocessed_texts(df, normalize_repeat, remove_symbols):
  return df["text"].astype(str).apply(
      lambda text: text_preprocessing.preprocess_text(
          text,
          normalize_repeat=normalize_repeat,
          remove_symbols=remove_symbols
      )
  )

preprocessing_conditions = {
    "raw": {
        "normalize_repeat": False,
        "remove_symbols": False
    },

    "repeat": {
        "normalize_repeat": True,
        "remove_symbols": False
    },

    "repeat_symbols": {
        "normalize_repeat": True,
        "remove_symbols": True
    }
}

In [10]:
# 전처리 적용 결과가 실제로 얼마나 달라지는지 확인

sample = train_df["text"].astype(str)

sample_repeat = sample.apply(
    lambda x: text_preprocessing.preprocess_text(
        x,
        normalize_repeat=True,
        remove_symbols=False
    )
)

sample_repeat_symbols = sample.apply(
    lambda x: text_preprocessing.preprocess_text(
        x,
        normalize_repeat=True,
        remove_symbols=True
    )
)

print(
    "raw -> repeat changed:",
    (sample != sample_repeat).sum()
)

print(
    "repeat -> repeat_symbols changed:",
    (sample_repeat != sample_repeat_symbols).sum()
)

print(
    "raw -> repeat_symbols changed:",
    (sample != sample_repeat_symbols).sum()
)

raw -> repeat changed: 13144
repeat -> repeat_symbols changed: 25198
raw -> repeat_symbols changed: 28865

In [11]:
# 반복문자 정규화로 실제 변경된 예시 확인

changed_repeat = sample != sample_repeat

for original, processed in zip(
    sample[changed_repeat].head(20),
    sample_repeat[changed_repeat].head(20)
):
    print("ORIGINAL :", original)
    print("REPEAT   :", processed)
    print("-" * 80)

ORIGINAL : 내가 톰행크스를 좋아하긴 했나보다... 초기 영화 빼고는 다 봤네.
REPEAT   : 내가 톰행크스를 좋아하긴 했나보다.. 초기 영화 빼고는 다 봤네.
--------------------------------------------------------------------------------
ORIGINAL : 미역은 원생생물계 산호초는 동물ㅇㅇ 아 미역이 바다의 새ㄱㅇㄱㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
REPEAT   : 미역은 원생생물계 산호초는 동물ㅇㅇ 아 미역이 바다의 새ㄱㅇㄱㅋㅋ
--------------------------------------------------------------------------------
ORIGINAL : 어릴 때 했던 건데 아직도 볼 때마다 뒤통수 얼얼함 ㅋㅋㅋㅋ
REPEAT   : 어릴 때 했던 건데 아직도 볼 때마다 뒤통수 얼얼함 ㅋㅋ
--------------------------------------------------------------------------------
ORIGINAL : 물갈이약 구매했어요...미미네에서 수조2개랑 여러가지 용품사면서 3~4번 주문했었는데 그 동안 만족했었는데... 약간 불량들이 있네요... 1) 함께 구매한 스포이드에 구멍이 있네요... 2) 부화통에 같이오는 흡착고무가 불량이라 안붙어요... 3) 예전에 구매한 온도계의 온도가 안맞아요...
REPEAT   : 물갈이약 구매했어요..미미네에서 수조2개랑 여러가지 용품사면서 3~4번 주문했었는데 그 동안 만족했었는데.. 약간 불량들이 있네요.. 1) 함께 구매한 스포이드에 구멍이 있네요.. 2) 부화통에 같이오는 흡착고무가 불량이라 안붙어요.. 3) 예전에 구매한 온도계의 온도가 안맞아요..
--------------------------------------------------------------------------------
ORIGINAL : 스토리 담당만 붙여줬으면 갓작품 됬을텐데.....
REPEAT   : 스토리 담당만 붙여줬으면 갓작품 됬을텐데..
--------------------------------------------------------------------------------
ORIGINAL : _ 원래 트위터는 배우는 재미가 쏠쏠함ㅋㅋ 일단 님 존재감은 확실히 심어주셨음ㅋㅋㅋ 일루와요. 완전 반가움ㅋㅋㅋㅋ
REPEAT   : _ 원래 트위터는 배우는 재미가 쏠쏠함ㅋㅋ 일단 님 존재감은 확실히 심어주셨음ㅋㅋ 일루와요. 완전 반가움ㅋㅋ
--------------------------------------------------------------------------------
ORIGINAL : 3분이나참다니   대단한대요
REPEAT   : 3분이나참다니  대단한대요
--------------------------------------------------------------------------------
ORIGINAL : 누렁이ㅋㅋ 아무튼 똘추님은 재미 있으신 분 같다는^^   ㅠ..ㅠ111
REPEAT   : 누렁이ㅋㅋ 아무튼 똘추님은 재미 있으신 분 같다는^^  ㅠ..ㅠ11
--------------------------------------------------------------------------------
ORIGINAL : 둘이모여야..이와오이..!!!!ㅠㅠㅠㅠㅋㅋㅋ1
REPEAT   : 둘이모여야..이와오이..!!ㅠㅠㅋㅋ1
--------------------------------------------------------------------------------
ORIGINAL : 특수.... 다른 나라도 대통령이 특수한 케이스인지? 저금리라 여기저기 다 올랐는데...ㅎㅎ언론과 일베가 난리치면 그런갑다 하는 사람 여기 또 있네요
REPEAT   : 특수.. 다른 나라도 대통령이 특수한 케이스인지? 저금리라 여기저기 다 올랐는데..ㅎㅎ언론과 일베가 난리치면 그런갑다 하는 사람 여기 또 있네요
--------------------------------------------------------------------------------
ORIGINAL : = 438덬 480덬 ???큰시장서 성공했다고 원래있던 계약을 일방적으로 파기하거나 변경할순없잖아 글고 일본시장 작은거아냐;;;
REPEAT   : = 438덬 480덬 ??큰시장서 성공했다고 원래있던 계약을 일방적으로 파기하거나 변경할순없잖아 글고 일본시장 작은거아냐;;
--------------------------------------------------------------------------------
ORIGINAL : 이게 잘하는거라니.... 연기력 대사톤..... 흠..  저번에 공개된 연습영상보다 쪼금 더 나아진거지 잘하는거라곤 할수없는듯..
REPEAT   : 이게 잘하는거라니.. 연기력 대사톤.. 흠..  저번에 공개된 연습영상보다 쪼금 더 나아진거지 잘하는거라곤 할수없는듯..
--------------------------------------------------------------------------------
ORIGINAL : 굿모닝 트친님들!!! 오늘도 소중한시간 즐거운하루되세요21
REPEAT   : 굿모닝 트친님들!! 오늘도 소중한시간 즐거운하루되세요21
--------------------------------------------------------------------------------
ORIGINAL : 진짜 사회악이  청취율 1위를 까는거야?? 법정제재는 니들 tv조선이 압도적 1위잖아?? 철면피같은 것들 악마가있다면 니들이 악마야!!! 아니다~~사탄도 니들보면 울고가겠다~~
REPEAT   : 진짜 사회악이  청취율 1위를 까는거야?? 법정제재는 니들 tv조선이 압도적 1위잖아?? 철면피같은 것들 악마가있다면 니들이 악마야!! 아니다~~사탄도 니들보면 울고가겠다~~
--------------------------------------------------------------------------------
ORIGINAL : 다운로드 할 시간도 아까운영화... 공짜로 보여줘도 시간이 더 아까운영화
REPEAT   : 다운로드 할 시간도 아까운영화.. 공짜로 보여줘도 시간이 더 아까운영화
--------------------------------------------------------------------------------
ORIGINAL : 저거 말고 수당이 다른명세서로 따로 나온다고 들었는네 아닌가...??
REPEAT   : 저거 말고 수당이 다른명세서로 따로 나온다고 들었는네 아닌가..??
--------------------------------------------------------------------------------
ORIGINAL : 분홍언니 머리 너무 찰떡인것.....
REPEAT   : 분홍언니 머리 너무 찰떡인것..
--------------------------------------------------------------------------------
ORIGINAL : 선댓글 후감상.. 햇님 업로드 기다렸어요~~~
REPEAT   : 선댓글 후감상.. 햇님 업로드 기다렸어요~~
--------------------------------------------------------------------------------
ORIGINAL : 소도 목욕하고 씻기면 엄청 귀여움 ㅋㅋㅋ
REPEAT   : 소도 목욕하고 씻기면 엄청 귀여움 ㅋㅋ
--------------------------------------------------------------------------------
ORIGINAL : 올챙이국수 보고 꼬리내려가는 길순 ㅋㅋㅋㅋ
REPEAT   : 올챙이국수 보고 꼬리내려가는 길순 ㅋㅋ
--------------------------------------------------------------------------------

In [12]:
# 선택적 기호 제거로 실제 변경된 예시 확인

changed_symbols = sample_repeat != sample_repeat_symbols

for before, after in zip(
    sample_repeat[changed_symbols].head(20),
    sample_repeat_symbols[changed_symbols].head(20)
):
    print("BEFORE :", before)
    print("AFTER  :", after)
    print("-" * 80)

BEFORE : 내가 톰행크스를 좋아하긴 했나보다.. 초기 영화 빼고는 다 봤네.
AFTER  : 내가 톰행크스를 좋아하긴 했나보다 초기 영화 빼고는 다 봤네
--------------------------------------------------------------------------------
BEFORE : 정말 상상을 초월하는 무개념 진상들 상대하다 우울증, 공항장애 걸리는 공무원 많아요 ㅠ 생각보다 스트레스 심한 직업군이라는 생각입니다.
AFTER  : 정말 상상을 초월하는 무개념 진상들 상대하다 우울증 공항장애 걸리는 공무원 많아요 ㅠ 생각보다 스트레스 심한 직업군이라는 생각입니다
--------------------------------------------------------------------------------
BEFORE : 새로운 세상과 조우한 자의 어린아이 같은 반응, 어쩌면 회복된 것은 눈이 아닌 순수함일지도 모르겠습니다. 그걸 가능케 한 사랑에 경의를 표합니다.
AFTER  : 새로운 세상과 조우한 자의 어린아이 같은 반응 어쩌면 회복된 것은 눈이 아닌 순수함일지도 모르겠습니다 그걸 가능케 한 사랑에 경의를 표합니다
--------------------------------------------------------------------------------
BEFORE : 물갈이약 구매했어요..미미네에서 수조2개랑 여러가지 용품사면서 3~4번 주문했었는데 그 동안 만족했었는데.. 약간 불량들이 있네요.. 1) 함께 구매한 스포이드에 구멍이 있네요.. 2) 부화통에 같이오는 흡착고무가 불량이라 안붙어요.. 3) 예전에 구매한 온도계의 온도가 안맞아요..
AFTER  : 물갈이약 구매했어요 미미네에서 수조2개랑 여러가지 용품사면서 3~4번 주문했었는데 그 동안 만족했었는데 약간 불량들이 있네요 1 함께 구매한 스포이드에 구멍이 있네요 2 부화통에 같이오는 흡착고무가 불량이라 안붙어요 3 예전에 구매한 온도계의 온도가 안맞아요
--------------------------------------------------------------------------------
BEFORE : 십일조는 겨우60인데? 나머지 다 어디감? 혹시 엄마아빠 그랜져따로타고, 외식자주하는거아님? 이런저런건 다빼고 십일조얘기만하는건 그냥 머리나쁜거ㅜ
AFTER  : 십일조는 겨우60인데? 나머지 다 어디감? 혹시 엄마아빠 그랜져따로타고 외식자주하는거아님? 이런저런건 다빼고 십일조얘기만하는건 그냥 머리나쁜거ㅜ
--------------------------------------------------------------------------------
BEFORE : 90년 줘야 하는거 아닌가?  쓰레기같은 것들.
AFTER  : 90년 줘야 하는거 아닌가? 쓰레기같은 것들
--------------------------------------------------------------------------------
BEFORE : 스토리 담당만 붙여줬으면 갓작품 됬을텐데..
AFTER  : 스토리 담당만 붙여줬으면 갓작품 됬을텐데
--------------------------------------------------------------------------------
BEFORE : 솔직히 말씀드릴게요. 맛없습니다. 장어라서 단백질원이 필요해서 오징어,연어,고등어,쇠고기 이것저것 먹느라 이번엔 장어를 선택해 봤는데 맛이 없어요. 장어상태가 좋은지 어떤지는 모르겠습니다. 다만 개별포장이 아니라서 하나씩 먹기도 어렵고 소스가 너무 맛이 없습니다. 마트에서 파는 장어초밥에 소스가 맛있다고 느껴질 정도. 운동때문에 단백질원이 필요한 분들은 뭐 이용하실 수도 있다고 생각하는데 맛있는 요리가 필요하신 분께는 비추입니다.
AFTER  : 솔직히 말씀드릴게요 맛없습니다 장어라서 단백질원이 필요해서 오징어 연어 고등어 쇠고기 이것저것 먹느라 이번엔 장어를 선택해 봤는데 맛이 없어요 장어상태가 좋은지 어떤지는 모르겠습니다 다만 개별포장이 아니라서 하나씩 먹기도 어렵고 소스가 너무 맛이 없습니다 마트에서 파는 장어초밥에 소스가 맛있다고 느껴질 정도 운동때문에 단백질원이 필요한 분들은 뭐 이용하실 수도 있다고 생각하는데 맛있는 요리가 필요하신 분께는 비추입니다
--------------------------------------------------------------------------------
BEFORE : 진작살껄그랬어요~안사고 그냥 넘길려고했는데 아기가 눕기싫어하고 바운서도 이제 싫어해서 어쩔수없이 늦게라도 샀어요 앉아있는모습이 참깜찍해요~비싸지만 카트랑 풀셋으로 구입하길 잘했네요ㅋㅋ 범*랑 젤리*이랑 토트..며칠동안 고민했는데 아주 만족해요^6^
AFTER  : 진작살껄그랬어요~안사고 그냥 넘길려고했는데 아기가 눕기싫어하고 바운서도 이제 싫어해서 어쩔수없이 늦게라도 샀어요 앉아있는모습이 참깜찍해요~비싸지만 카트랑 풀셋으로 구입하길 잘했네요ㅋㅋ 범 랑 젤리 이랑 토트 며칠동안 고민했는데 아주 만족해요 6
--------------------------------------------------------------------------------
BEFORE : _ 원래 트위터는 배우는 재미가 쏠쏠함ㅋㅋ 일단 님 존재감은 확실히 심어주셨음ㅋㅋ 일루와요. 완전 반가움ㅋㅋ
AFTER  : _ 원래 트위터는 배우는 재미가 쏠쏠함ㅋㅋ 일단 님 존재감은 확실히 심어주셨음ㅋㅋ 일루와요 완전 반가움ㅋㅋ
--------------------------------------------------------------------------------
BEFORE : 자사주 매입 효과 최고봉은 자사주 소각이다.
AFTER  : 자사주 매입 효과 최고봉은 자사주 소각이다
--------------------------------------------------------------------------------
BEFORE : 3분이나참다니  대단한대요
AFTER  : 3분이나참다니 대단한대요
--------------------------------------------------------------------------------
BEFORE : 누렁이ㅋㅋ 아무튼 똘추님은 재미 있으신 분 같다는^^  ㅠ..ㅠ11
AFTER  : 누렁이ㅋㅋ 아무튼 똘추님은 재미 있으신 분 같다는 ㅠ ㅠ11
--------------------------------------------------------------------------------
BEFORE : 민주당소속 대통령도 모욕하는 느그지지자와  이낙연의원에게  악성댓글다는 dear moon부터 출당시키자
AFTER  : 민주당소속 대통령도 모욕하는 느그지지자와 이낙연의원에게 악성댓글다는 dear moon부터 출당시키자
--------------------------------------------------------------------------------
BEFORE : 맹세하고 내가 찍은거. 캐나다 살고있는데 집에서 걸어서 5분거리에 볼수있는 풍경임
AFTER  : 맹세하고 내가 찍은거 캐나다 살고있는데 집에서 걸어서 5분거리에 볼수있는 풍경임
--------------------------------------------------------------------------------
BEFORE : 사랑의 주님, 근신하라 깨어라. 너희 대적 마귀가 우는 사자같이 두루 다니며 삼킬 자를 찾고 있다는 말씀을 상기하면서 깨어 있는 믿음의 사람 되게 하옵소서!112
AFTER  : 사랑의 주님 근신하라 깨어라 너희 대적 마귀가 우는 사자같이 두루 다니며 삼킬 자를 찾고 있다는 말씀을 상기하면서 깨어 있는 믿음의 사람 되게 하옵소서!112
--------------------------------------------------------------------------------
BEFORE : 둘이모여야..이와오이..!!ㅠㅠㅋㅋ1
AFTER  : 둘이모여야 이와오이 !!ㅠㅠㅋㅋ1
--------------------------------------------------------------------------------
BEFORE : 특수.. 다른 나라도 대통령이 특수한 케이스인지? 저금리라 여기저기 다 올랐는데..ㅎㅎ언론과 일베가 난리치면 그런갑다 하는 사람 여기 또 있네요
AFTER  : 특수 다른 나라도 대통령이 특수한 케이스인지? 저금리라 여기저기 다 올랐는데 ㅎㅎ언론과 일베가 난리치면 그런갑다 하는 사람 여기 또 있네요
--------------------------------------------------------------------------------
BEFORE : = 438덬 480덬 ??큰시장서 성공했다고 원래있던 계약을 일방적으로 파기하거나 변경할순없잖아 글고 일본시장 작은거아냐;;
AFTER  : 438덬 480덬 ??큰시장서 성공했다고 원래있던 계약을 일방적으로 파기하거나 변경할순없잖아 글고 일본시장 작은거아냐
--------------------------------------------------------------------------------
BEFORE : 따분한 감성팔이 영화, 주연 배우의 연기력이 무색한 연출과 스토리라인
AFTER  : 따분한 감성팔이 영화 주연 배우의 연기력이 무색한 연출과 스토리라인
--------------------------------------------------------------------------------

In [13]:
THRESHOLDS = np.arange(0.10, 0.61, 0.05)

TFIDF_PARAMS = {
    "ngram_range": (1, 2),
    "min_df": 2,
    "max_features": 50000,
    "sublinear_tf": True
}


def run_lr_experiment(
    train_texts,
    val_texts,
    y_train,
    y_val
):
    vectorizer = TfidfVectorizer(**TFIDF_PARAMS)

    X_train = vectorizer.fit_transform(train_texts)
    X_val = vectorizer.transform(val_texts)

    model = OneVsRestClassifier(
        LogisticRegression(
            max_iter=1000
        )
    )

    train_start = time.perf_counter()

    model.fit(
        X_train,
        y_train
    )

    train_time = time.perf_counter() - train_start

    inference_start = time.perf_counter()

    y_val_prob = model.predict_proba(
        X_val
    )

    inference_time = time.perf_counter() - inference_start

    threshold_rows = []

    for threshold in THRESHOLDS:

        y_val_pred = metrics.apply_threshold(
            y_val_prob,
            threshold=float(threshold)
        )

        result = metrics.evaluate_multilabel(
            y_val,
            y_val_pred,
            y_val_prob
        )

        threshold_rows.append({
            "threshold": round(float(threshold), 2),
            "micro_f1": result["micro_f1"],
            "macro_f1": result["macro_f1"],
            "hamming_loss": result["hamming_loss"]
        })

    threshold_df = pd.DataFrame(
        threshold_rows
    )

    probability_metrics = metrics.evaluate_multilabel(
        y_val,
        metrics.apply_threshold(y_val_prob, 0.5),
        y_val_prob
    )

    return {
        "vectorizer": vectorizer,
        "model": model,
        "y_val_prob": y_val_prob,
        "threshold_results": threshold_df,
        "pr_auc_micro": probability_metrics["pr_auc_micro"],
        "pr_auc_macro": probability_metrics["pr_auc_macro"],
        "train_time": train_time,
        "inference_time": inference_time,
        "vocab_size": len(vectorizer.vocabulary_)
    }

In [15]:
experiments = {}

for condition_name, condition in preprocessing_conditions.items():
  print(f"Running: {condition_name}")

  train_texts = make_preprocessed_texts(
      train_df,
      normalize_repeat=condition["normalize_repeat"],
      remove_symbols=condition["remove_symbols"]
  )

  val_texts = make_preprocessed_texts(
      val_df,
      normalize_repeat=condition["normalize_repeat"],
      remove_symbols=condition["remove_symbols"]
  )

  experiments[condition_name] = run_lr_experiment(
      train_texts,
      val_texts,
      y_train,
      y_val
  )

  print("Done")

Running: raw
Done
Running: repeat
Done
Running: repeat_symbols
Done

In [17]:
for condition_name, experiment in experiments.items():
    print(
        condition_name,
        experiment["vocab_size"]
    )

raw 50000
repeat 50000
repeat_symbols 50000

In [18]:
best_rows = []

for condition_name, experiment in experiments.items():

    threshold_df = experiment["threshold_results"]

    best = threshold_df.sort_values(
        by=[
            "micro_f1",
            "macro_f1",
            "hamming_loss"
        ],
        ascending=[
            False,
            False,
            True
        ]
    ).iloc[0]

    best_rows.append({
        "preprocessing": condition_name,
        "threshold": best["threshold"],
        "micro_f1": best["micro_f1"],
        "macro_f1": best["macro_f1"],
        "hamming_loss": best["hamming_loss"],
        "pr_auc_micro": experiment["pr_auc_micro"],
        "pr_auc_macro": experiment["pr_auc_macro"],
        "train_time": experiment["train_time"],
        "inference_time": experiment["inference_time"],
        "vocab_size": experiment["vocab_size"]
    })

comparison_df = pd.DataFrame(best_rows)

comparison_df

,preprocessing,threshold,micro_f1,macro_f1,hamming_loss,pr_auc_micro,pr_auc_macro,train_time,inference_time,vocab_size
0,raw,0.25,0.511358,0.364154,0.201227,0.521789,0.394299,78.407964,0.034366,50000
1,repeat,0.25,0.512276,0.365655,0.200636,0.523327,0.395635,83.445783,0.037410,50000
2,repeat_symbols,0.25,0.512276,0.365655,0.200636,0.523327,0.395635,83.782313,0.077956,50000

In [19]:
comparison_df = comparison_df.sort_values(
    by=[
        "micro_f1",
        "macro_f1",
        "hamming_loss"
    ],
    ascending=[
        False,
        False,
        True
    ]
).reset_index(drop=True)

comparison_df

,preprocessing,threshold,micro_f1,macro_f1,hamming_loss,pr_auc_micro,pr_auc_macro,train_time,inference_time,vocab_size
0,repeat,0.25,0.512276,0.365655,0.200636,0.523327,0.395635,83.445783,0.037410,50000
1,repeat_symbols,0.25,0.512276,0.365655,0.200636,0.523327,0.395635,83.782313,0.077956,50000
2,raw,0.25,0.511358,0.364154,0.201227,0.521789,0.394299,78.407964,0.034366,50000

In [20]:
BEST_PREPROCESSING = comparison_df.iloc[0]["preprocessing"]
BEST_THRESHOLD = float(comparison_df.iloc[0]["threshold"])

print("Best preprocessing:", BEST_PREPROCESSING)
print("Best threshold:", BEST_THRESHOLD)

Best preprocessing: repeat
Best threshold: 0.25

In [21]:
best_experiment = experiments[BEST_PREPROCESSING]

best_model = best_experiment["model"]
best_vectorizer = best_experiment["vectorizer"]
best_val_prob = best_experiment["y_val_prob"]

best_val_pred = metrics.apply_threshold(
    best_val_prob,
    BEST_THRESHOLD
)

In [22]:
final_val_metrics = metrics.evaluate_multilabel(
    y_val,
    best_val_pred,
    best_val_prob
)

final_val_metrics

{'micro_f1': 0.5122759718017281,
 'macro_f1': 0.36565462491667183,
 'hamming_loss': 0.20063636363636364,
 'pr_auc_macro': np.float64(0.3956354319329758),
 'pr_auc_micro': np.float64(0.5233272362468584)}

In [23]:
label_f1_df = metrics.get_label_wise_f1(
    y_val,
    best_val_pred
)

train_label_counts = y_train.sum(axis=0)

label_f1_df["train_count"] = train_label_counts

label_f1_df = label_f1_df[
    [
        "label_id",
        "label",
        "train_count",
        "f1"
    ]
]

label_f1_df.sort_values(
    "f1",
    ascending=False
)

    label_id        label  train_count        f1
0          0        불평/불만        16696  0.674715
10        10      안타까움/실망        17465  0.656762
23        23         어이없음        15996  0.648189
22        22           짜증        14930  0.634897
6          6        화남/분노        12299  0.610465
28        28       즐거움/신남        10867  0.581201
20        20          한심함        12201  0.579897
42        42           기쁨         9967  0.572024
2          2        감동/감탄        10778  0.568688
12        12        의심/불신        11565  0.547741
8          8          기대감        11197  0.538815
31        31        증오/혐오         7684  0.532455
15        15       신기함/관심        10638  0.517950
1          1        환영/호의         9252  0.510413
40        40           행복         7473  0.508316
43        43        안심/신뢰         7929  0.497059
4          4          고마움         5181  0.482999
33        33        당황/난처         9996  0.480296
16        16         아껴주는         7173  0.465508
37        37         재미없음         3691  0.400598
29        29          깨달음         8151  0.392589
39        39           놀람         7355  0.365629
3          3         지긋지긋         6386  0.352635
41        41        불안/걱정         7541  0.346981
32        32  흐뭇함(귀여움/예쁨)         4401  0.341772
38        38       불쌍함/연민         5451  0.323982
7          7           존경         3854  0.311111
14        14        편안/쾌적         3771  0.306785
24        24           없음         6344  0.304981
13        13          뿌듯함         5229  0.301422
5          5           슬픔         4137  0.286897
9          9      우쭐댐/무시함         6002  0.265134
34        34           경악         5193  0.234957
21        21     역겨움/징그러움         3864  0.208909
11        11          비장함         3352  0.192593
27        27        힘듦/지침         3769  0.162866
35        35      부담/안_내킴         4768  0.112175
19        19           절망         3652  0.096475
26        26          귀찮음         2428  0.065672
36        36          서러움         2031  0.061303
25        25      패배/자기혐오         1581  0.031250
17        17         부끄러움         2329  0.013699
18        18       공포/무서움         1194  0.000000
30        30          죄책감          698  0.000000

In [24]:
label_f1_df.sort_values(
    "f1",
    ascending=True
).head(15)

    label_id     label  train_count        f1
30        30       죄책감          698  0.000000
18        18    공포/무서움         1194  0.000000
17        17      부끄러움         2329  0.013699
25        25   패배/자기혐오         1581  0.031250
36        36       서러움         2031  0.061303
26        26       귀찮음         2428  0.065672
19        19        절망         3652  0.096475
35        35   부담/안_내킴         4768  0.112175
27        27     힘듦/지침         3769  0.162866
11        11       비장함         3352  0.192593
21        21  역겨움/징그러움         3864  0.208909
34        34        경악         5193  0.234957
9          9   우쭐댐/무시함         6002  0.265134
5          5        슬픔         4137  0.286897
13        13       뿌듯함         5229  0.301422

In [25]:
label_f1_df.sort_values(
    "train_count",
    ascending=True
).head(15)

    label_id        label  train_count        f1
30        30          죄책감          698  0.000000
18        18       공포/무서움         1194  0.000000
25        25      패배/자기혐오         1581  0.031250
36        36          서러움         2031  0.061303
17        17         부끄러움         2329  0.013699
26        26          귀찮음         2428  0.065672
11        11          비장함         3352  0.192593
19        19           절망         3652  0.096475
37        37         재미없음         3691  0.400598
27        27        힘듦/지침         3769  0.162866
14        14        편안/쾌적         3771  0.306785
7          7           존경         3854  0.311111
21        21     역겨움/징그러움         3864  0.208909
5          5           슬픔         4137  0.286897
32        32  흐뭇함(귀여움/예쁨)         4401  0.341772

In [26]:
error_count = 0

for i in range(len(val_df)):

    true_ids = np.where(
        y_val[i] == 1
    )[0]

    pred_ids = np.where(
        best_val_pred[i] == 1
    )[0]

    if set(true_ids) != set(pred_ids):

        print("TEXT:")
        print(val_df.iloc[i]["text"])

        print("TRUE:")
        print([
            utils_labels.LABELS[j]
            for j in true_ids
        ])

        print("PRED:")
        print([
            utils_labels.LABELS[j]
            for j in pred_ids
        ])

        print("-" * 80)

        error_count += 1

        if error_count == 10:
            break

TEXT:
음료가 몇푼이나 한다고.. 미국같으면 바로 바꿔줄텐데 참 어이없네요 그 카페
TRUE:
['불평/불만', '화남/분노', '안타까움/실망', '짜증', '어이없음', '서러움']
PRED:
['불평/불만', '화남/분노', '안타까움/실망', '의심/불신', '한심함', '짜증', '어이없음', '즐거움/신남', '당황/난처']
--------------------------------------------------------------------------------
TEXT:
아버님 끝까지 진실이 밝혀질때까지 응원합니다.
TRUE:
['환영/호의', '감동/감탄', '존경', '기대감', '비장함', '신기함/관심', '아껴주는', '불쌍함/연민', '안심/신뢰']
PRED:
['환영/호의', '감동/감탄', '고마움', '존경', '기대감', '안타까움/실망', '신기함/관심', '아껴주는', '안심/신뢰']
--------------------------------------------------------------------------------
TEXT:
대응이 잘못됐어 차라리 그냥 철없던 시절 그랬었다고 인정하고 울면서 자숙하는 시늉만 했어도 이렇게까지 최악은 아니었을텐데
TRUE:
['불평/불만', '안타까움/실망', '의심/불신', '한심함', '짜증', '어이없음', '증오/혐오', '서러움']
PRED:
['불평/불만', '화남/분노', '안타까움/실망', '의심/불신', '한심함', '짜증', '어이없음', '당황/난처']
--------------------------------------------------------------------------------
TEXT:
저번주 일요일 지리산둘레길엘 갔다왔습니다. "강호동,은지원 코스" 상상이하!!! 기대가 컸던 만큼 실망도 크더군요.
TRUE:
['불평/불만', '안타까움/실망', '짜증']
PRED:
['불평/불만', '안타까움/실망', '의심/불신', '신기함/관심', '어이없음', '없음', '즐거움/신남']
--------------------------------------------------------------------------------
TEXT:
이 짤 매력 터지죠. 진짜 역대 월드컵 미녀 짤 중 최고인듯요. 짤로만 ㅋ
TRUE:
['환영/호의', '감동/감탄', '존경', '기대감', '우쭐댐/무시함', '신기함/관심', '즐거움/신남', '흐뭇함(귀여움/예쁨)', '행복']
PRED:
['불평/불만', '환영/호의', '감동/감탄', '화남/분노', '안타까움/실망', '의심/불신', '신기함/관심', '한심함', '짜증', '어이없음', '즐거움/신남', '증오/혐오', '놀람', '기쁨']
--------------------------------------------------------------------------------
TEXT:
귀여우시다 ㅋㅋㅋㅋㅋㅋ 나도 딸냄 크면 써먹어야지.. 500원 모아서 치킨 사먹기.. 메모...
TRUE:
['환영/호의', '감동/감탄', '기대감', '신기함/관심', '즐거움/신남', '깨달음', '흐뭇함(귀여움/예쁨)', '기쁨']
PRED:
['감동/감탄', '기대감', '신기함/관심', '한심함', '없음', '즐거움/신남', '깨달음', '기쁨']
--------------------------------------------------------------------------------
TEXT:
문재앙 수괴늠의 시계, 아니 세상은 거꾸로 돈다.
TRUE:
['불평/불만', '화남/분노', '의심/불신', '짜증', '증오/혐오']
PRED:
['불평/불만', '지긋지긋', '화남/분노', '안타까움/실망', '의심/불신', '신기함/관심', '한심함', '짜증', '어이없음', '증오/혐오', '당황/난처', '놀람', '불안/걱정']
--------------------------------------------------------------------------------
TEXT:
똥 주위에 똥파리만 가득한건 당연한 일이지... 그걸 똥인지 된장인지 구별 못하고 열성당원 자처하며 충성하는 ㄷㄲ도 똥... 내년엔 똥 말고 된장 좀 담급시다.
TRUE:
['불평/불만', '지긋지긋', '화남/분노', '안타까움/실망', '의심/불신', '한심함', '짜증', '증오/혐오', '당황/난처']
PRED:
['불평/불만', '지긋지긋', '화남/분노', '안타까움/실망', '의심/불신', '한심함', '짜증', '어이없음', '증오/혐오']
--------------------------------------------------------------------------------
TEXT:
목 뒷 부분에 케이블 타이가 있길래 뭐지? 하면서 잘랐더니 몸통과 분리가 되더라고요... 아니 애기들 장난감에 케이블 타이가 뭡니까 ㅋㅋㅋ 놀래서 집에 있는 케이블 타이로 원상 복구 했네요 원래 모양 그대로에요 사진에 보이는 대로 되어 있었네요 ㅋ 정녕 케이블타이 말고는 방법이 없었나요 ㅋㅋㅋㅋ
TRUE:
['불평/불만', '화남/분노', '우쭐댐/무시함', '안타까움/실망', '한심함', '짜증', '어이없음', '즐거움/신남', '당황/난처', '경악', '놀람']
PRED:
['불평/불만', '화남/분노', '안타까움/실망', '의심/불신', '한심함', '짜증', '어이없음', '즐거움/신남', '깨달음', '당황/난처']
--------------------------------------------------------------------------------
TEXT:
도칠이는 마징가귀가 이상하게 잘어울려요 ㅎㅎㅎ
TRUE:
['감동/감탄', '신기함/관심', '아껴주는', '즐거움/신남', '깨달음', '흐뭇함(귀여움/예쁨)']
PRED:
['환영/호의', '감동/감탄', '기대감', '신기함/관심', '즐거움/신남', '깨달음', '흐뭇함(귀여움/예쁨)', '행복', '기쁨', '안심/신뢰']
--------------------------------------------------------------------------------

In [ ]:
comparison_df.to_csv(
    os.path.join(
        RESULTS_DIR,
        "week04_lr_preprocessing_comparison.csv"
    ),
    index=False,
    encoding="utf-8-sig"
)

label_f1_df.to_csv(
    os.path.join(
        RESULTS_DIR,
        "week04_lr_label_f1.csv"
    ),
    index=False,
    encoding="utf-8-sig"
)

In [ ]:
import os

ARTIFACT_DIR = "/content/drive/MyDrive/26_KOTE/artifacts/week4_lr"

os.makedirs(ARTIFACT_DIR, exist_ok=True)

print("ARTIFACT_DIR:", ARTIFACT_DIR)
print("exists:", os.path.exists(ARTIFACT_DIR))

ARTIFACT_DIR: /content/drive/MyDrive/26_KOTE/artifacts/week4_lr
exists: True

In [ ]:
joblib.dump(
    best_model,
    os.path.join(
        ARTIFACT_DIR,
        "logistic_regression.joblib"
    )
)

joblib.dump(
    best_vectorizer,
    os.path.join(
        ARTIFACT_DIR,
        "tfidf_vectorizer.joblib"
    )
)

joblib.dump(
    mlb,
    os.path.join(
        ARTIFACT_DIR,
        "multilabel_binarizer.joblib"
    )
)

['/content/drive/MyDrive/26_KOTE/artifacts/week4_lr/multilabel_binarizer.joblib']

In [ ]:
best_condition = preprocessing_conditions[
    BEST_PREPROCESSING
]

config = {
    "model": "Logistic Regression",
    "vectorizer": "TF-IDF",

    "preprocessing": BEST_PREPROCESSING,

    "normalize_repeat":
        best_condition["normalize_repeat"],

    "remove_symbols":
        best_condition["remove_symbols"],

    "threshold":
        BEST_THRESHOLD,

    "num_labels":
        NUM_LABELS,

    "tfidf": {
        "ngram_range": [1, 2],
        "min_df": 2,
        "max_features": 50000,
        "sublinear_tf": True
    }
}

with open(
    os.path.join(
        ARTIFACT_DIR,
        "config.json"
    ),
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        config,
        f,
        ensure_ascii=False,
        indent=2
    )

In [ ]:
print(os.listdir(ARTIFACT_DIR))

['logistic_regression.joblib', 'tfidf_vectorizer.joblib', 'multilabel_binarizer.joblib', 'config.json']

In [ ]:
!ls /content

drive  sample_data  Self-Project